import Head from "next/head";
import { useAuth } from "../_app";
import { Box } from "@mantine/core";
import { useEffect } from "react";
import { useRouter } from "next/router";
import LoginForm from "../../components/loginForm";
import { onValue, push, ref } from "firebase/database";
import { db } from "../../config";

const Home = () => {
	const { user } = useAuth();
	const Router = useRouter();

	useEffect(() => {
		if (user) {
			Router.push("/");

			onValue(ref(db, "/users"), (snapshot) => {
				const accountsArr = Object.values(snapshot.val());

				for (let i = 0; i < accountsArr.length; i++) {
					if (user.uid !== accountsArr[i].userId) {
						push(ref(db, "/users"), {
							email: user.email,
							userId: user.uid,
							createdAt: user.metadata.createdAt,
						});

						return false;
					}
				}
			});
		}
	}, [user]);
	return (
		<Box sx={{ display: "grid", placeItems: "center", height: "90vh" }}>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<LoginForm />
		</Box>
	);
};

export default Home;
