import Head from "next/head";
import RegisterForm from "../../components/registerForm";
import { Box } from "@mantine/core";

const Home = () => {
	return (
		<Box sx={{ display: "grid", placeItems: "center", height: "90vh" }}>
			<Head>
				<title>Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<RegisterForm />
		</Box>
	);
};

export default Home;
