import { Button } from "@mantine/core";
import Head from "next/head";
import { useAuth } from "./_app";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home = () => {
	const Router = useRouter();
	const { user } = useAuth();

	useEffect(() => {
		if (!user) {
			Router.push("/login");
		}
	}, [user]);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Button>test</Button>
			</div>
		</div>
	);
};

export default Home;
