import { Box, Text } from "@mantine/core";
import Head from "next/head";
import { useAuth } from "./_app";
import { useEffect } from "react";
import { useRouter } from "next/router";
import CodePostInput from "../components/codePostInput";
import CodePosts from "../components/codePosts";
import { useMediaQuery } from "@mantine/hooks";

const Home = () => {
	const mobile = useMediaQuery("(max-width: 768px)");

	const Router = useRouter();
	const { user } = useAuth();

	useEffect(() => {
		if (!user) {
			Router.push("/login");
		}
	}, [Router, user]);
	return (
		<Box
			sx={{
				position: "relative",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				padding: `2.5% ${mobile ? "5%" : "15%"}`,
			}}
		>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{user && (
				<>
					<CodePostInput />
					<CodePosts />
				</>
			)}
		</Box>
	);
};

export default Home;
