import { Box, Text } from "@mantine/core";
import Head from "next/head";
import { useAuth } from "./_app";
import { useEffect } from "react";
import { useRouter } from "next/router";
import CodePostInput from "../components/codePostInput";
import CodePosts from "../components/codePosts";

const Home = () => {
	const Router = useRouter();
	const { user } = useAuth();

	useEffect(() => {
		if (!user) {
			Router.push("/login");
		}
	}, [user]);
	return (
		<Box
			sx={{
				position: "relative",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				padding: "2.5% 15%",
			}}
		>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{user && (
				<Box>
					<Box sx={{ position: "absolute", right: "5em", top: "2.5em" }}>
						<Text>{user.email}</Text>
					</Box>
					<CodePostInput />
					<CodePosts />
				</Box>
			)}
		</Box>
	);
};

export default Home;
